### ISSUE TITLE
Searching Customers

### ISSUE THREAD

**Issue by akreu** [justbetter/laravel-magento-client#12]
Getting the following error when trying to query customers:

```
$searchCriteria = SearchCriteria::make()
            ->paginate(1, 50)
            ->where('email', 'like', '%@test.com')
            ->get();

return $this->magento->get('customers', $searchCriteria);
```

Which returns: 
`{"message":"Request does not match any route."}`

Anything I'm missing?

**Comment by VincentBean** [comment]
You should be using the endpoint `customers/search`

See [Magento's API docs](https://developer.adobe.com/commerce/webapi/rest/quick-reference/)

**Comment by akreu** [comment]
> You should be using the endpoint `customers/search`
> 
> See [Magento's API docs](https://developer.adobe.com/commerce/webapi/rest/quick-reference/)

Ah gotcha, yep that worked perfectly, thank you!
