### ISSUE TITLE
Select items - searchCriteria

### ISSUE THREAD

**Issue by gotanasro19** [justbetter/laravel-magento-client#18]
Hi,

this select return 0 orders

$searchCriteria = \JustBetter\MagentoClient\Query\SearchCriteria::make()
            ->select(['entity_id','increment_id'])
            ->where('entity_id', '=', '399824')
            ->get();

but  this return order

$searchCriteria = \JustBetter\MagentoClient\Query\SearchCriteria::make()
            ->where('entity_id', '=', '399824')
            ->get();

where is a problem?

**Comment by VincentBean** [comment]
Yes, this is because Magento returns the orders in a nested 'items' array so you would have to do this:

```
$searchCriteria = \JustBetter\MagentoClient\Query\SearchCriteria::make()
    ->select(['items[entity_id,increment_id']])
    ->where('entity_id', '=', '399824')
    ->get();
```

**Comment by gotanasro19** [comment]
thank you
