### ISSUE TITLE
Unable to Activate Integration

### ISSUE THREAD

**Issue by apexdivision** [justbetter/laravel-magento-client#22]
Hello.

I am trying to install this package.

Environment:

MacOS 13.4.1
PHP 8.1
Laravel 10.14.1
Magento 2.4.6

Both Laravel & Mage domains are local with .test tld.

.env set with MAGENTO_BASE_URL pointing to local domain
and MAGENTO_AUTH_METHOD=oauth

No issues during installation, but when I am trying to activate the integration at Magento, I get:
The attempt to post data to consumer failed due to an unexpected error. Please try again later.

Debug log:

```
[2023-07-16T17:03:00.516376+00:00] main.CRITICAL: Laminas\Http\Exception\RuntimeException: Unable to read response, or response is empty in /Users/nir/htdocs/projects/artee/m2/vendor/laminas/laminas-http/src/Client.php:973
Stack trace:
#0 /Users/nir/htdocs/projects/artee/m2/vendor/magento/module-integration/Model/OauthService.php(245): Laminas\Http\Client->send()
#1 /Users/nir/htdocs/projects/artee/m2/vendor/magento/module-integration/Controller/Adminhtml/Integration/TokensExchange.php(59): Magento\Integration\Model\OauthService->postToConsumer('2', 'https://intrane...')
#2 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange->execute()
#3 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->___callParent('execute', Array)
#4 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->Magento\Framework\Interception\{closure}()
#5 /Users/nir/htdocs/projects/artee/m2/generated/code/Magento/Integration/Controller/Adminhtml/Integration/TokensExchange/Interceptor.php(23): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->___callPlugins('execute', Array, Array)
#6 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/App/Action/Action.php(111): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->execute()
#7 /Users/nir/htdocs/projects/artee/m2/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->___callParent('dispatch', Array)
#10 /Users/nir/htdocs/projects/artee/m2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /Users/nir/htdocs/projects/artee/m2/generated/code/Magento/Integration/Controller/Adminhtml/Integration/TokensExchange/Interceptor.php(32): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->___callPlugins('dispatch', Array, Array)
#14 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/App/FrontController.php(245): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor), Object(Magento\Framework\App\Request\Http))
#16 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor))
#17 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#19 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /Users/nir/htdocs/projects/artee/m2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#21 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /Users/nir/htdocs/projects/artee/m2/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#23 /Users/nir/htdocs/projects/artee/m2/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#24 /Users/nir/htdocs/projects/artee/m2/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#25 {main} {"exception":"[object] (Laminas\\Http\\Exception\\RuntimeException(code: 0): Unable to read response, or response is empty at /Users/nir/htdocs/projects/artee/m2/vendor/laminas/laminas-http/src/Client.php:973)"} []
[2023-07-16T17:03:00.622119+00:00] main.INFO: Broken reference: the 'notification.messages' tries to reorder itself towards 'user', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
```

Directly accessing identity endpoint at /magento/oauth/identity throws 403 error.

Please advise what I am missing.

Thank you
Regards,

Nir Banerjee

**Comment by ramonrietdijk** [comment]
Hi Nir Banerjee,

The endpoint will result in a 403 when the `MAGENTO_AUTH_METHOD` is not set to `oauth`, but since you have, I think it may have to do with caching.

Could you try to clear all caches?

```
php artisan optimize:clear
```

**Comment by apexdivision** [comment]
@ramonrietdijk 

Hi There!

Thank you for the tip.
I have already tried that, it didn't help.

In fact I use a small shell script which I execute whenever any change is made, essentially it does:

php artisan optimize:clear && php artisan cache:clear && php artisan route:clear && php artisan config:clear && php artisan view:clear && php artisan event:clear && npm run build

Thank you anyway.

Is it only me or anyone else also faced similar problem? Cause I couldn't find any similar issue in repo issues.

Any pointer to get this resolved will be very helpful.

Thank you
Regards
Nir

**Comment by ramonrietdijk** [comment]
Hi @apexdivision 

We have not received any issues regarding this before.

Magento 2 will post to the `callback` endpoint first. This way, Laravel knows what credentials to accept to establish an OAuth 1 connection. The output in your log file may suggest that this call has failed. 

Do you have a Magento2 OAuth secret file in your Laravel project? It is by default located at:

```
./storage/app/secret/magento2_oauth.json
```

The `callback` endpoint does not have any middleware except the authentication method check I've mentioned in my previous response.

If the file is missing, could you try to hit the `callback` endpoint manually?

```bash
curl --include --request POST \
--header "Accept: application/json" \
--header "Content-Type: application/json" \
--data '{"oauth_consumer_key": "x", "oauth_consumer_secret": "x", "oauth_verifier": "x"}' \
http://localhost/magento/oauth/callback
```

You should get a 200 status code and `magento2_oauth.json` should be filled.

**Comment by apexdivision** [comment]
Hi @ramonrietdijk 

Thank you for the suggestion.

No, magento2_oauth.json file was not created.

But when I executed below, as per your advise:

```
nir@Nirjhareswars-MacBook-Pro ~ % curl --include --request POST \
--header "Accept: application/json" \
--header "Content-Type: application/json" \
--data '{"oauth_consumer_key": "x", "oauth_consumer_secret": "x", "oauth_verifier": "x"}' \
https://intranet_dev.artee.test/magento/oauth/callback
HTTP/1.1 200 OK
Date: Mon, 17 Jul 2023 06:13:53 GMT
Server: Apache/2.4.57 (Unix) OpenSSL/3.1.1 PHP/8.1.21
X-Powered-By: PHP/8.2.8
Cache-Control: no-cache, private
Transfer-Encoding: chunked
Content-Type: application/json

[]%                                                                             nnnnnnnnninnnnnnnnnnnnir@Nirjhareswars-MacBook-Pro ~ % php -v
PHP 8.1.21 (cli) (built: Jul 13 2023 08:13:23) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.21, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.21, Copyright (c), by Zend Technologies
```

It created the file storage/app/secret/magento2_oauth.json

`{"callback":{"oauth_consumer_key":"x","oauth_consumer_secret":"x","oauth_verifier":"x"}}`

Does it mean magento failing to execute the request? But debug log shows the request was sent.

Not sure if this is important, my laravel install uses jetstream and auth is handled by laratrust, but I have not added any middleware in this package, yet.

Kindly advice.

Thank you,
Nir

**Comment by apexdivision** [comment]
The issue is probably due to the self signed certificates I am using for both local domains, though the certificate is added into keychain but seems Magento's laminas http client and adapter is enabled with ssl verification which is causing the problem.

**Comment by ramonrietdijk** [comment]
I've installed a fresh copy of Magento 2.4.6 and I can activate the OAuth integration.

Do you get any errors from cURL? Could you perhaps add a `dd` in the `read`-method?

```
./vendor/magento/framework/HTTP/Adapter/Curl.php

public function read()
{
    $response = curl_exec($this->_getResource());
    if ($response === false) {
        dd(curl_error($this->_getResource()));

        return '';
    }

    ...
}
```

**Comment by apexdivision** [comment]
Hi @ramonrietdijk 

Okay, so first I added dd and the mage admin won't load, throwing error:
"SSL certificate problem: self-signed certificate"

Commented the dd line, admin opens fine, navigated to the step just before activation, I mean till the "Allow" step in integration activation, then enabled dd line.

Next mage admin shows a popup, saying: "Sorry, something went wrong. Please try again later."
Probably because it was not getting the formatted response from server.

Inspected the url which was returning malformed data:

`https://m2.artee.test/mage_admin/admin/integration/tokensExchange/id/1/reauthorize/0/key/d87d92bcd44b3ab41c39665356ac12347f478a43405837ee4fde07b040075b71/?form_key=yqnQhOWDQQssncgk&_=1689583141503`

And response was same:

"SSL certificate problem: self-signed certificate"

So now we know the problem. But, the certificate is already in keychain and no browser (safari, chrome, brave, FF dev edition) complains opening the urls (both laravel and mage).

But how do I override this? I need to get this rolling on my dev environment. Live deployment should not create any problem since both live domain have proper SSL, but for testing I must get it running on local.
Is modifying core file(s) is the only way out?

Thank you

**Comment by ramonrietdijk** [comment]
I'm not really sure what the best options are to accomplish this. Since it's a self-signed certificate and you're working locally, the easiest solution would be to just use HTTP instead.

Otherwise, I'm afraid you may have to modify these files directly or make use of a patch. Note that disabling any certificate checks defeats the purpose of using SSL in the first place.

I think it's also safe to say that this isn't an issue with the library itself. I'm closing the issue. Feel free to reopen it if any problems occur aside from SSL.

**Comment by samuel-olavo** [comment]
I have the same problem.
