### ISSUE TITLE
Dependency Injection - newbie question

### ISSUE THREAD

**Issue by rickjm540** [justbetter/laravel-magento-client#24]
Hello!

Thank you for contributing your time and talents for this!
I am currently using the greyloon api package and it works well - but I am unfamiliar with how to use your software as a client rather than as a facade. Can you give me a brief example of what it is you are passing to the "Example" class (the $magento object comes from where?) 

Thanks and sorry for the newbie question!

**Comment by ramonrietdijk** [comment]
Hi Rick!

We make use of dependency injection in Laravel. This means that Laravel will instantiate this class for us. More information about this process can be read in the [documentation](https://laravel.com/docs/10.x/container#introduction).

If a constructor is unavailable to you, you could always make use of the `app` helper like so:

```php
$magento = app(\JustBetter\MagentoClient\Client\Magento::class);
$magento->get('...');
```

Hope this helps!

**Comment by rickjm540** [comment]
Wow - this is really cool :) 
I need to learn more about dependency injection!

Thanks for the quick response and help :)

Rick

**Comment by ramonrietdijk** [comment]
You're welcome!
