### ISSUE TITLE
Bulk Support

### ISSUE THREAD

**Issue by lucassmacedo** [justbetter/laravel-magento-client#26]
Hello! This package doest have support to bulk requests?

**Comment by VincentBean** [comment]
I'm assuming that you are referencing to the `V1/bulk` endpoints, any endpoint that is available in the Magento 2 API is supported. So yes, you can call the `V1/bulk` endpoints with this package.

**Comment by lucassmacedo** [comment]
OK. I will submit a PR with a modification to facilitate the bulk request into the package.
