### ISSUE TITLE
Connecting magento2-Laravel

### ISSUE THREAD

**Issue by samuel-olavo** [justbetter/laravel-magento-client#30]
Hello, i need help to connect laravel to magento2. I'm not getting it.

**Comment by VincentBean** [comment]
Please explain your issue

**Comment by samuel-olavo** [comment]
I did composer require justbetter/laravel-magento. but I have some questions. When I create access to the Magento2 API, do I have to specify the callback url? How can I check if the connection is working?
I don't know and I needed help!

**Comment by samuel-olavo** [comment]
for example, when i do this, i have this error:

php artisan magento:price:import-customer-groups

   Illuminate\Validation\ValidationException 

  The oauth consumer key field is required. (and 3 more errors)

  at vendor/laravel/framework/src/Illuminate/Support/helpers.php:330
    326▕     function throw_if($condition, $exception = 'RuntimeException', ...$parameters)
    327▕     {
    328▕         if ($condition) {
    329▕             if (is_string($exception) && class_exists($exception)) {
  ➜ 330▕                 $exception = new $exception(...$parameters);
    331▕             }
    332▕ 
    333▕             throw is_string($exception) ? new RuntimeException($exception) : $exception;
    334▕         }

      +46 vendor frames 

  47  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by VincentBean** [comment]
Please refer to the documentation of this package and Magento to setup authentication. This is not an issue with this package which is why I'm closing this issue.
