### ISSUE TITLE
Bulk

### ISSUE THREAD

**Issue by samuel-olavo** [justbetter/laravel-magento-client#39]
Hello,
I am trying to make a post:
$response = $this->magento->post('/rest/default/async/bulk/V1/inventory/source-items',
but it always gives a route error.

"message":"The request does not match any route.

Could you possibly provide some support, please?

Thank you very much.

**Comment by VincentBean** [comment]
Hi, this is because the client builds the base URL.
Use the [postBulk](https://github.com/justbetter/laravel-magento-client/blob/main/src/Client/Magento.php#L81) method like this:
```php
$response = $this->magento->postBulk('inventory/source-items',
```
