### ISSUE TITLE
Issue with JustBetter\MagentoClient: "Call to undefined method connection()"

### ISSUE THREAD

**Issue by samuel-olavo** [justbetter/laravel-magento-client#40]
Hello,

I am currently encountering an error with the JustBetter MagentoClient in a Laravel project. I have set up multiple connections in the magento.php configuration file as follows:

php
'connections' => [
    'default' => [
        'base_url' => env('MAGENTO_BASE_URL'),
        'base_path' => env('MAGENTO_BASE_PATH', 'rest'),
        'store_code' => env('MAGENTO_STORE_CODE', 'all'),
        'version' => env('MAGENTO_API_VERSION', 'V1'),
        'access_token' => env('MAGENTO_ACCESS_TOKEN'),
        'timeout' => 30,
        'connect_timeout' => 10,
        'authentication_method' => env('MAGENTO_AUTH_METHOD', 'token'),
    ],
    'xsign' => [
        'base_url' => env('MAGENTO_BASE_URL_XSIGN'),
        'base_path' => env('MAGENTO_BASE_PATH', 'rest'),
        'store_code' => env('MAGENTO_STORE_CODEXSIGN', 'xsign'),
        'version' => env('MAGENTO_API_VERSION', 'V1'),
        'access_token' => env('MAGENTO_ACCESS_TOKEN_XSIGN'),
        'timeout' => 30,
        'connect_timeout' => 10,
        'authentication_method' => env('MAGENTO_AUTH_METHOD', 'token'),
    ],
]
When I attempt to use the connection() method to specify which configuration to use ('xsign' in this case), I receive the following error:

Error
Call to undefined method JustBetter\MagentoClient\Client\Magento::connection()
at app/Console/Commands/Xsign/SyncClientesToMagento.php:87
This occurs when trying to execute the command: $response = $this->magento->connection('xsign')->get($url, $queryParams);

I've checked the documentation and tried to ensure that my setup aligns with the provided examples, but I'm stuck on how to resolve this error. Could this be a version issue, or am I missing something in my implementation?

Thank you for any guidance you can provide.

**Comment by VincentBean** [comment]
Hi, could you please double check what `$this->magento` is ? 
It should be an instance of `\JustBetter\MagentoClient\Client\Magento` which contains the method.

**Comment by samuel-olavo** [comment]
public function __construct(
        protected \JustBetter\MagentoClient\Client\Magento $magento,
    ) {
        parent::__construct(); // Isso garante que a classe pai Command seja corretamente inicializada.
    }

**Comment by VincentBean** [comment]
I cannot reproduce this with version 2.4. Your configuration and call seem correct. 

This is working fine:
```php
 $response = $this->magento->connection('default')->put('products/'.urlencode($model->sku), $payload);
```

[See the tests too on how to use multiple connections](https://github.com/justbetter/laravel-magento-client/blob/main/tests/Client/MultiConnectionTest.php#L42)

**Comment by samuel-olavo** [comment]
Problem 5
    - justbetter/laravel-magento-stock is locked to version 1.2.7 and an update of this package was not requested.
    - justbetter/laravel-magento-stock 1.2.7 requires justbetter/laravel-magento-client ^1.4 -> found justbetter/laravel-magento-client[1.4.0, 1.5.0, 1.x-dev] but it conflicts with your root composer.json require (^2.4).

**Comment by VincentBean** [comment]
Yes, version 1.x of this package does not support multiple connections. `justbetter/laravel-magento-stock` is compatible with version 2.4, update both and it should work.
