### ISSUE TITLE
The GET method is not supported for route magento/oauth/callback/default. Supported methods: POST.

### ISSUE THREAD

**Issue by Koen-Outlawz** [justbetter/laravel-magento-client#45]
Im getting this error when going to the callback url, is this something known and why isn't it working? The route in the package clearly says its a post.

<?php

use Illuminate\Support\Facades\Route;
use JustBetter\MagentoClient\Http\Controllers\OAuthController;

Route::post('callback/{connection}', [OAuthController::class, 'callback'])
    ->name('magento.oauth.callback');

Route::get('identity/{connection}', [OAuthController::class, 'identity'])
    ->middleware(config('magento.oauth.middleware'))
    ->name('magento.oauth.identity');

**Comment by VincentBean** [comment]
Hi Koen, could you give a bit more information? What are you trying to do? What error do you get?

**Comment by Koen-Outlawz** [comment]
I get the next error when visiting https://my-app/magento/oauth/callback/default The GET method is not supported for route magento/oauth/callback/default. Supported methods: POST.

Im trying to get my app connected to my magento store

This is my magento config:
<?php

return [

    'connection' => 'default',

    'connections' => [
        'default' => [
            /* Base URL of Magento, for example: https://magento.test */
            'base_url' => env('MAGENTO_BASE_URL'),

            /* Base path, only modify if your API is not at /rest */
            'base_path' => env('MAGENTO_BASE_PATH', 'rest'),

            /* Graphql path, only modify if your API is not at /graphql */
            'graphql_path' => env('MAGENTO_GRAPHQL_PATH', 'graphql'),

            /* Store code, modify if you want to set a store by default. */
            'store_code' => env('MAGENTO_STORE_CODE', 'all'),

            /* Modify if Magento has a new API version */
            'version' => env('MAGENTO_API_VERSION', 'V1'),

            /* Magento access token of an integration */
            'access_token' => env('MAGENTO_ACCESS_TOKEN'),

            /* Specify the timeout (in seconds) for the request. */
            'timeout' => 30,

            /* Specify the connection timeout (in seconds) for the request. */
            'connect_timeout' => 10,

            /* Authentication method, choose either "oauth" or "token". */
            'authentication_method' => env('MAGENTO_AUTH_METHOD', 'oauth'),

            /* Availability configuration. */
            'availability' => [
                /* The response codes that should trigger the availability check. */
                'codes' => [502, 503, 504],

                /* The amount of failed requests before the service is marked as unavailable. */
                'threshold' => 10,

                /* The timespan in minutes in which the failed requests should occur. */
                'timespan' => 10,

                /* The cooldown in minutes after the threshold is reached. */
                'cooldown' => 2,
            ],
        ],
    ],

    /* OAuth configuration */
    'oauth' => [
        'middleware' => [
            'auth',
        ],
        'prefix' => 'magento/oauth',
        'keystore' => \JustBetter\MagentoClient\OAuth\KeyStore\DatabaseKeyStore::class,
    ],
];

**Comment by VincentBean** [comment]
Please review the package's README, it seems that you have flipped the identity and callback URL's.

**Comment by Koen-Outlawz** [comment]
Where did you get that from? I didn't flip anything, below is the web.php that is in the package the callback is a post but I still get this error when visiting the callback url: The GET method is not supported for route magento/oauth/callback/default. Supported methods: POST.

So where is the get coming from?

<?php

use Illuminate\Support\Facades\Route;
use JustBetter\MagentoClient\Http\Controllers\OAuthController;

Route::post('callback/{connection}', [OAuthController::class, 'callback'])
    ->name('magento.oauth.callback');

Route::get('identity/{connection}', [OAuthController::class, 'identity'])
    ->middleware(config('magento.oauth.middleware'))
    ->name('magento.oauth.identity');

**Comment by VincentBean** [comment]
Please refer to the readme and Magento docs on how to set this up. Alternatively you can use an access token.
